name: pandoc

on:
  push:
    paths:
      - "**pandoc.yml"
      - "**.md"
      - "!README.md"

jobs:
  render-output:
    name: Render documents
    
    runs-on: ubuntu-22.04
    container: 
      image: ms609/pandoc
      options: --user-root

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Update git
        run: |
          apt update
          apt install -y git
          git --version
          
    
      - uses: actions/checkout@v3
        repository: ms609/packages

      - name: Render html
        run: |
          pandoc CONTRIBUTING.md -o CONTRIBUTING.html
          pandoc CODE_OF_CONDUCT.md -o CODE_OF_CONDUCT.html

      - name: Deploy
        run: |
          dir
          git add *.html
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git diff-index --quiet HEAD || git commit -m "Render HTML"
          git fetch
          git pull --ff-only
          git push
